import "./globals.css"
import { fontBig,fontSmall,modern } from "./Font";

export const metadata = {
  title: "SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontBig.variable} ${fontSmall.variable} fsmall ${modern.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
